name: Selenium Tests

on:
  push:
    branches:
      - main 
      - tests
      - day1Tests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Change this to your desired Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run Selenium tests
      run: npm run test

    - name: Save Debug Log
      if: always() # Ensure this step runs even if previous steps fail
      run: mkdir -p $GITHUB_WORKSPACE/logs && mv /home/runner/.npm/_logs/* $GITHUB_WORKSPACE/logs/

    - name: Upload Debug Log
      if: always() # Ensure this step runs even if previous steps fail
      uses: actions/upload-artifact@v2
      with:
        name: debug-log
        path: $GITHUB_WORKSPACE/logs
