name: Selenium Tests

on:
  push:
    branches:
      - main 
      - tests
      - testSprint2
      - testSprint3
      - testSprint4
      - day1Tests
      - day2Tests
      - day3Tests
      - day4Tests
      - day5Tests
      - day6Tests
      - day7Tests
      - day8Tests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' 

    - name: Install dependencies
      run: npm install

    - name: Run Selenium tests
      run: npm run test

