name: Selenium Tests

on:
  push:
    branches:
      -tests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      -name: checkout code
       uses: actions/checkout@v2

      -name: Node.js Setup
       uses: actions/setup-node@v2
       with:
        node-version: 20
      
      -name: Install dependencies
        run: npm install
      
      # -name: Run Tests
      # -run: npm run test
      
